[package]
name = "ordinator-orchestrator"
version = "0.1.0"
edition = "2024"

[dependencies]
ordinator-actors = { path = "../ordinator-actors" }
ordinator-contracts = { path = "../ordinator-contracts" }
ordinator-scheduling-environment = { path = "../ordinator-scheduling-environment" }
anyhow = { workspace = true }

