[[supervisors]]
id = "main"
number_of_supervisor_periods = 3
assets = [ "Df" ]

# [[supervisors]]
# id = "supervisor-second"
################################
###          MTN-ELEC        ###
################################
[[operational]]
id = "OP-01-001"
resources = ["MTN-ELEC" ]
hours_per_day = 6.0
operational_configuration.off_shift_interval = { start = "19:00:00", end = "07:00:00" }
operational_configuration.break_interval = { start = "11:00:00", end = "12:00:00" }
operational_configuration.toolbox_interval = { start = "07:00:00", end = "08:00:00" }
operational_configuration.availability.start_date = "2025-01-13T07:00:00Z"
operational_configuration.availability.finish_date = "2025-01-27T15:00:00Z"
assets = [ "Df" ]

[[operational]]
id = "OP-01-002"
resources = [ "MTN-ELEC" ]
hours_per_day = 6.0
operational_configuration.off_shift_interval = { start = "19:00:00", end = "07:00:00" }
operational_configuration.break_interval = { start = "11:00:00", end = "12:00:00" }
operational_configuration.toolbox_interval = { start = "07:00:00", end = "08:00:00" }
operational_configuration.availability.start_date = "2025-01-13T07:00:00Z"
operational_configuration.availability.finish_date = "2025-01-27T15:00:00Z"
assets = [ "Df" ]

################################
###          MTN-INST        ###
################################
[[operational]]
id = "OP-02-001"
resources = [ "MTN-INST" ]
hours_per_day = 6.0
operational_configuration.off_shift_interval = { start = "19:00:00", end = "07:00:00" }
operational_configuration.break_interval = { start = "11:00:00", end = "12:00:00" }
operational_configuration.toolbox_interval = { start = "07:00:00", end = "08:00:00" }
operational_configuration.availability.start_date = "2025-01-13T07:00:00Z"
operational_configuration.availability.finish_date = "2025-01-27T15:00:00Z"
assets = [ "Df" ]

[[operational]]
id = "OP-02-002"
resources = [ "MTN-INST" ]
hours_per_day = 6.0
operational_configuration.off_shift_interval = { start = "19:00:00", end = "07:00:00" }
operational_configuration.break_interval = { start = "11:00:00", end = "12:00:00" }
operational_configuration.toolbox_interval = { start = "07:00:00", end = "08:00:00" }
operational_configuration.availability.start_date = "2025-01-13T07:00:00Z"
operational_configuration.availability.finish_date = "2025-01-27T15:00:00Z"
assets = [ "Df" ]

################################
###          MTN-MECH        ###
################################
[[operational]]
id = "OP-02-001"
resources = [ "MTN-MECH" ]
hours_per_day = 6.0
operational_configuration.off_shift_interval = { start = "19:00:00", end = "07:00:00" }
operational_configuration.break_interval = { start = "11:00:00", end = "12:00:00" }
operational_configuration.toolbox_interval = { start = "07:00:00", end = "08:00:00" }
operational_configuration.availability.start_date = "2025-01-13T07:00:00Z"
operational_configuration.availability.finish_date = "2025-01-27T15:00:00Z"
assets = [ "Df" ]

[[operational]]
id = "OP-02-002"
resources = [ "MTN-MECH" ]
hours_per_day = 6.0
operational_configuration.off_shift_interval = { start = "19:00:00", end = "07:00:00" }
operational_configuration.break_interval = { start = "11:00:00", end = "12:00:00" }
operational_configuration.toolbox_interval = { start = "07:00:00", end = "08:00:00" }
operational_configuration.availability.start_date = "2025-01-13T07:00:00Z"
operational_configuration.availability.finish_date = "2025-01-27T15:00:00Z"
assets = [ "Df" ]

################################
###          MTN-TURB        ###
################################
[[operational]]
id = "OP-03-001"
resources = [ "MTN-TURB"]
hours_per_day = 6.0
operational_configuration.off_shift_interval = { start = "19:00:00", end = "07:00:00" }
operational_configuration.break_interval = { start = "11:00:00", end = "12:00:00" }
operational_configuration.toolbox_interval = { start = "07:00:00", end = "08:00:00" }
operational_configuration.availability.start_date = "2025-01-13T07:00:00Z"
operational_configuration.availability.finish_date = "2025-01-27T15:00:00Z"
assets = [ "Df" ]

[[operational]]
id = "OP-03-002"
resources = [ "MTN-TURB"]
hours_per_day = 6.0
operational_configuration.off_shift_interval = { start = "19:00:00", end = "07:00:00" }
operational_configuration.break_interval = { start = "11:00:00", end = "12:00:00" }
operational_configuration.toolbox_interval = { start = "07:00:00", end = "08:00:00" }
operational_configuration.availability.start_date = "2025-01-13T07:00:00Z"
operational_configuration.availability.finish_date = "2025-01-27T15:00:00Z"
assets = [ "Df" ]

################################
###          MTN-TELE        ###
################################
[[operational]]
id = "OP-03-001"
resources = [ "MTN-TELE"]
hours_per_day = 6.0
operational_configuration.off_shift_interval = { start = "19:00:00", end = "07:00:00" }
operational_configuration.break_interval = { start = "11:00:00", end = "12:00:00" }
operational_configuration.toolbox_interval = { start = "07:00:00", end = "08:00:00" }
operational_configuration.availability.start_date = "2025-01-13T07:00:00Z"
operational_configuration.availability.finish_date = "2025-01-27T15:00:00Z"
assets = [ "Df" ]

################################
###          MTN-ROUS        ###
################################
[[operational]]
id = "OP-04-001"
resources = [ "MTN-ROUS"]
hours_per_day = 6.0
operational_configuration.off_shift_interval = { start = "19:00:00", end = "07:00:00" }
operational_configuration.break_interval = { start = "11:00:00", end = "12:00:00" }
operational_configuration.toolbox_interval = { start = "07:00:00", end = "08:00:00" }
operational_configuration.availability.start_date = "2025-01-13T07:00:00Z"
operational_configuration.availability.finish_date = "2025-01-27T15:00:00Z"
assets = [ "Df" ]

[[operational]]
id = "OP-04-002"
resources = [ "MTN-ROUS"]
hours_per_day = 6.0
operational_configuration.off_shift_interval = { start = "19:00:00", end = "07:00:00" }
operational_configuration.break_interval = { start = "11:00:00", end = "12:00:00" }
operational_configuration.toolbox_interval = { start = "07:00:00", end = "08:00:00" }
operational_configuration.availability.start_date = "2025-01-13T07:00:00Z"
operational_configuration.availability.finish_date = "2025-01-27T15:00:00Z"
assets = [ "Df" ]


################################
###          MEDIC           ###
################################
[[operational]]
id = "OP-05-001"
resources = [ "MEDIC" ]
hours_per_day = 6.0
operational_configuration.off_shift_interval = { start = "19:00:00", end = "07:00:00" }
operational_configuration.break_interval = { start = "11:00:00", end = "12:00:00" }
operational_configuration.toolbox_interval = { start = "07:00:00", end = "08:00:00" }
operational_configuration.availability.start_date = "2025-01-13T07:00:00Z"
operational_configuration.availability.finish_date = "2025-01-27T15:00:00Z"
assets = [ "Df" ]

################################
###          MTN-LAGG        ###
################################
[[operational]]
id = "OP-05-001"
resources = [ "MTN-LAGG"]
hours_per_day = 6.0
operational_configuration.off_shift_interval = { start = "19:00:00", end = "07:00:00" }
operational_configuration.break_interval = { start = "11:00:00", end = "12:00:00" }
operational_configuration.toolbox_interval = { start = "07:00:00", end = "08:00:00" }
operational_configuration.availability.start_date = "2025-01-13T07:00:00Z"
operational_configuration.availability.finish_date = "2025-01-27T15:00:00Z"
assets = [ "Df" ]


################################
###          MTN-PAIN        ###
################################
[[operational]]
id = "OP-06-001"
resources = [ "MTN-PAIN"]
hours_per_day = 6.0
operational_configuration.off_shift_interval = { start = "19:00:00", end = "07:00:00" }
operational_configuration.break_interval = { start = "11:00:00", end = "12:00:00" }
operational_configuration.toolbox_interval = { start = "07:00:00", end = "08:00:00" }
operational_configuration.availability.start_date = "2025-01-13T07:00:00Z"
operational_configuration.availability.finish_date = "2025-01-27T15:00:00Z"
assets = [ "Df" ]

################################
###          MTN-PIPF        ###
################################
[[operational]]
id = "OP-07-001"
resources = [ "MTN-PIPF"]
hours_per_day = 6.0
operational_configuration.off_shift_interval = { start = "19:00:00", end = "07:00:00" }
operational_configuration.break_interval = { start = "11:00:00", end = "12:00:00" }
operational_configuration.toolbox_interval = { start = "07:00:00", end = "08:00:00" }
operational_configuration.availability.start_date = "2025-01-13T07:00:00Z"
operational_configuration.availability.finish_date = "2025-01-27T15:00:00Z"
assets = [ "Df" ]
[[operational]]
id = "OP-07-002"
resources = [ "MTN-PIPF"]
hours_per_day = 6.0
operational_configuration.off_shift_interval = { start = "19:00:00", end = "07:00:00" }
operational_configuration.break_interval = { start = "11:00:00", end = "12:00:00" }
operational_configuration.toolbox_interval = { start = "07:00:00", end = "08:00:00" }
operational_configuration.availability.start_date = "2025-01-13T07:00:00Z"
operational_configuration.availability.finish_date = "2025-01-27T15:00:00Z"
assets = [ "Df" ]

################################
###          MTN-ROPE        ###
################################
[[operational]]
id = "OP-08-001"
resources = [ "MTN-ROPE"]
hours_per_day = 6.0
operational_configuration.off_shift_interval = { start = "19:00:00", end = "07:00:00" }
operational_configuration.break_interval = { start = "11:00:00", end = "12:00:00" }
operational_configuration.toolbox_interval = { start = "07:00:00", end = "08:00:00" }
operational_configuration.availability.start_date = "2025-01-13T07:00:00Z"
operational_configuration.availability.finish_date = "2025-01-27T15:00:00Z"
assets = [ "Df" ]
[[operational]]
id = "OP-08-002"
resources = [ "MTN-ROPE"]
hours_per_day = 6.0
operational_configuration.off_shift_interval = { start = "19:00:00", end = "07:00:00" }
operational_configuration.break_interval = { start = "11:00:00", end = "12:00:00" }
operational_configuration.toolbox_interval = { start = "07:00:00", end = "08:00:00" }
operational_configuration.availability.start_date = "2025-01-13T07:00:00Z"
operational_configuration.availability.finish_date = "2025-01-27T15:00:00Z"
assets = [ "Df" ]

################################
###          MTN-SCAF        ###
################################
[[operational]]
id = "OP-09-001"
resources = [ "MTN-SCAF"]
hours_per_day = 6.0
operational_configuration.off_shift_interval = { start = "19:00:00", end = "07:00:00" }
operational_configuration.break_interval = { start = "11:00:00", end = "12:00:00" }
operational_configuration.toolbox_interval = { start = "07:00:00", end = "08:00:00" }
operational_configuration.availability.start_date = "2025-01-13T07:00:00Z"
operational_configuration.availability.finish_date = "2025-01-27T15:00:00Z"
assets = [ "Df" ]
[[operational]]
id = "OP-09-002"
resources = [ "MTN-SCAF"]
hours_per_day = 6.0
operational_configuration.off_shift_interval = { start = "19:00:00", end = "07:00:00" }
operational_configuration.break_interval = { start = "11:00:00", end = "12:00:00" }
operational_configuration.toolbox_interval = { start = "07:00:00", end = "08:00:00" }
operational_configuration.availability.start_date = "2025-01-13T07:00:00Z"
operational_configuration.availability.finish_date = "2025-01-27T15:00:00Z"
assets = [ "Df" ]

################################
###          INP-SITE        ###
################################
[[operational]]
id = "OP-10-001"
resources = [ "INP-SITE"]
hours_per_day = 6.0
operational_configuration.off_shift_interval = { start = "19:00:00", end = "07:00:00" }
operational_configuration.break_interval = { start = "11:00:00", end = "12:00:00" }
operational_configuration.toolbox_interval = { start = "07:00:00", end = "08:00:00" }
operational_configuration.availability.start_date = "2025-01-13T07:00:00Z"
operational_configuration.availability.finish_date = "2025-01-27T15:00:00Z"
assets = [ "Df" ]
[[operational]]
id = "OP-10-002"
resources = [ "INP-SITE"]
hours_per_day = 6.0
operational_configuration.off_shift_interval = { start = "19:00:00", end = "07:00:00" }
operational_configuration.break_interval = { start = "11:00:00", end = "12:00:00" }
operational_configuration.toolbox_interval = { start = "07:00:00", end = "08:00:00" }
operational_configuration.availability.start_date = "2025-01-13T07:00:00Z"
operational_configuration.availability.finish_date = "2025-01-27T15:00:00Z"
assets = [ "Df" ]

################################
###          PRODTECH        ###
################################
[[operational]]
id = "OP-11-001"
resources = [ "PRODTECH"]
hours_per_day = 6.0
operational_configuration.off_shift_interval = { start = "19:00:00", end = "07:00:00" }
operational_configuration.break_interval = { start = "11:00:00", end = "12:00:00" }
operational_configuration.toolbox_interval = { start = "07:00:00", end = "08:00:00" }
operational_configuration.availability.start_date = "2025-01-13T07:00:00Z"
operational_configuration.availability.finish_date = "2025-01-27T15:00:00Z"
assets = [ "Df" ]
[[operational]]
id = "OP-11-002"
resources = [ "PRODTECH"]
hours_per_day = 6.0
operational_configuration.off_shift_interval = { start = "19:00:00", end = "07:00:00" }
operational_configuration.break_interval = { start = "11:00:00", end = "12:00:00" }
operational_configuration.toolbox_interval = { start = "07:00:00", end = "08:00:00" }
operational_configuration.availability.start_date = "2025-01-13T07:00:00Z"
operational_configuration.availability.finish_date = "2025-01-27T15:00:00Z"
assets = [ "Df" ]
[[operational]]
id = "OP-11-003"
resources = [ "PRODTECH"]
hours_per_day = 6.0
operational_configuration.off_shift_interval = { start = "19:00:00", end = "07:00:00" }
operational_configuration.break_interval = { start = "11:00:00", end = "12:00:00" }
operational_configuration.toolbox_interval = { start = "07:00:00", end = "08:00:00" }
operational_configuration.availability.start_date = "2025-01-13T07:00:00Z"
operational_configuration.availability.finish_date = "2025-01-27T15:00:00Z"
assets = [ "Df" ]

# mtnelec = 3.5
# mtninst = 2.5
# mtnmech = 4.5
# mtncran = 0.0
# mtnturb = 3.0
# mtntele = 3.0
# mtnrous = 3.0
# medic = 1.0
# mtnlagg = 2.0
# mtnpain = 3.0
# mtnpipf = 4.0
# mtnrigg = 2.0
# mtnrope = 3.5
# mtnsat = 0.0
# mtnscaf = 3.5
# inpsite = 3.0
# prodlabo = 0.0
# prodtech = 5.0
# venacco = 0.0
# vencomm = 0.0
# venelec = 0.0
# venhvac = 0.0
# veninsp = 0.0
# veninst = 0.0
# venmech = 0.0
# venmete = 0.0
# venrope = 0.0
# venscaf = 0.0
# vensubs = 0.0
# vencran = 0.0
# qaqcelec = 0.0
# qaqcmech = 0.0
# qaqcpain = 0.0
# wellsupv = 0.0


