[strategic]
id = "strategic"
asset = "Df"
strategic_options.number_of_removed_work_orders = 25
strategic_options.urgency_weight = 1
strategic_options.resource_penalty_weight = 1000000
strategic_options.clustering_weight = 1000

[tactical]
id = "tactical"
asset = "Df"
tactical_options.number_of_removed_work_orders = 25
tactical_options.urgency = 1
tactical_options.resource_penalty = 10000000

[[supervisors]]
id = "main"
number_of_supervisor_periods = 3
assets = [ "Df" ]
supervisor_options.number_of_removed_work_orders = 15

# [[supervisors]]
# id = "supervisor-second"

################################
###          MTN-ELEC        ###
################################
[[operational]]
id = "OP-01-001"
resources = [ "MEDIC" ]
hours_per_day = 0.0
operational_options.number_of_removed_work_orders = 15
operational_configuration.off_shift_interval = { start = "19:00:00", end = "07:00:00" }
operational_configuration.break_interval = { start = "11:00:00", end = "12:00:00" }
operational_configuration.toolbox_interval = { start = "07:00:00", end = "08:00:00" }
operational_configuration.availability.start_date = "2025-01-13T07:00:00Z"
operational_configuration.availability.finish_date = "2025-01-27T15:00:00Z"
assets = [ "Df" ]

