[package]
name = "ordinator-orchestrator-actor-traits"
version = "0.1.0"
edition = "2024"

[dependencies]
ordinator-scheduling-environment ={ path = "../ordinator-scheduling-environment"}

anyhow = {workspace = true}
flume = {workspace = true}

