mtnelec = 4.5
mtninst = 4.5
mtnmech = 5.5
mtncran = 0.0
mtnturb = 4.0
mtntele = 4.0
mtnrous = 4.0
medic = 1.0
mtnlagg = 3.0
mtnpain = 4.0
mtnpipf = 5.0
mtnrigg = 3.0
mtnrope = 4.5
mtnsat = 2.0
mtnscaf = 4.5
inpsite = 4.0
prodlabo = 0.0
prodtech = 6.0
venacco = 0.0
vencomm = 0.0
venelec = 0.0
venhvac = 0.0
veninsp = 0.0
veninst = 0.0
venmech = 0.0
venmete = 0.0
venrope = 0.0
venscaf = 0.0
vensubs = 0.0
vencran = 0.0
qaqcelec = 0.0
qaqcmech = 0.0
qaqcpain = 0.0
wellsupv = 0.0
