mtnelec = 2.5
mtninst = 2.5
mtnmech = 2.5
mtncran = 0.0
mtnturb = 2.0
mtntele = 2.0
mtnrous = 2.0
medic = 1.0
mtnlagg = 1.0
mtnpain = 2.0
mtnpipf = 2.0
mtnrigg = 1.0
mtnrope = 2.5
mtnsat = 0.0
mtnscaf = 2.5
inpsite = 2.0
prodlabo = 0.0
prodtech = 3.0
venacco = 0.0
vencomm = 0.0
venelec = 0.0
venhvac = 0.0
veninsp = 0.0
veninst = 0.0
venmech = 0.0
venmete = 0.0
venrope = 0.0
venscaf = 0.0
vensubs = 0.0
vencran = 0.0
qaqcelec = 0.0
qaqcmech = 0.0
qaqcpain = 0.0
wellsupv = 0.0
