[strategic]
id = "strategic"
asset = "Df"
strategic_options.number_of_removed_work_orders = 25
strategic_options.urgency_weight = 1
strategic_options.resource_penalty_weight = 1000000
strategic_options.clustering_weight = 1000

material_to_period.nmat = 0
material_to_period.smat = 0
material_to_period.cmat = 2
material_to_period.pmat = 3
material_to_period.wmat = 3

[tactical]
id = "tactical"
asset = "Df"
tactical_options.number_of_removed_work_orders = 25
tactical_options.urgency = 1
tactical_options.resource_penalty = 10000000

material_to_period.nmat = 0
material_to_period.smat = 0
material_to_period.cmat = 2
material_to_period.pmat = 3
material_to_period.wmat = 3

# Resources are here given in people
mtnelec = 1.5
mtninst = 1.5
mtnmech = 3.5
mtncran = 0.0
mtnturb = 1.0
mtntele = 1.0
mtnrous = 3.0
medic = 0.0
mtnlagg = 0.0
mtnpain = 0.0
mtnpipf = 0.0
mtnrigg = 2.0
mtnrope = 2.5
mtnsat = 0.0
mtnscaf = 2.5
inpsite = 0.0
prodlabo = 0.0
prodtech = 2.5
venacco = 0.0
vencomm = 0.0
venelec = 0.0
venhvac = 0.0
veninsp = 0.0
veninst = 0.0
venmech = 0.0
venmete = 0.0
venrope = 0.0
venscaf = 0.0
vensubs = 0.0
vencran = 0.0
qaqcelec = 0.0
qaqcmech = 0.0
qaqcpain = 0.0
wellsupv = 0.0
