# Throttling in milliseconds (ms)
strategic_throttling   = 100
tactical_throttling    = 100
supervisor_throttling  = 100
operational_throttling = 100

# If you did not fix it, it aint fixed. I think that this is the
# best approach that we could have towards this.l
