[package]
name = "ordinator-conversions"
version = "0.1.0"
edition = "2024"

[dependencies]
ordinator-configuration ={ path = "../ordinator-configuration"}
ordinator-contracts ={ path = "../ordinator-contracts"}
ordinator-scheduling-environment ={ path = "../ordinator-scheduling-environment"}
