# Resources are here given in people
MtnElec = 0.5
MtnInst = 0.5
MtnMech = 1.5
MtnCran = 0.0
MtnTurb = 0.0
MtnTele = 1.0
MtnRous = 2.0
Medic = 0.0
MtnLagg = 0.0
MtnPain = 2.0
MtnPipf = 2.0
MtnRigg = 2.0
MtnRope = 2.0
MtnSat = 0.0
MtnScaf = 2.0
InpSite = 0.0
Prodlabo = 0.0
Prodtech = 2.0
VenAcco = 0.0
VenComm = 0.0
VenElec = 0.0
VenHvac = 0.0
VenInsp = 0.0
VenInst = 0.0
VenMech = 0.0
VenMete = 0.0
VenRope = 0.0
VenScaf = 0.0
VenSubs = 0.0
VenCran = 0.0
QaqcElec = 0.0
QaqcMech = 0.0
QaqcPain = 0.0
WellSupv = 0.0
