[sap-data-paths]
mid_functional_locations = "temp_scheduling_environment_database/mid_functional_locations.csv"
mid_operations_status    = "temp_scheduling_environment_database/mid_operations_status.csv"
mid_secondary_locations  = "temp_scheduling_environment_database/mid_secondary_locations.csv"
mid_work_center          = "temp_scheduling_environment_database/mid_work_center.csv"
mid_work_operations      = "temp_scheduling_environment_database/mid_work_operations.csv"
mid_work_orders          = "temp_scheduling_environment_database/mid_work_orders.csv"
mid_work_orders_status   = "temp_scheduling_environment_database/mid_work_orders_status.csv"



