 
[[supervisors]]
id = "main"
number_of_supervisor_periods = 3

# [[supervisors]]
# id = "supervisor-second"
################################
###          MTN-ELEC        ###
################################
[[operational]]
id = "OP-01-001"
resources.resources = [ "MTN-MECH", "MTN-ELEC", "PRODTECH" ]
hours_per_day = 6.0
operational_configuration.off_shift_interval = { start = "19:00:00",  end = "07:00:00" }
operational_configuration.break_interval = { start = "11:00:00", end = "12:00:00" }
operational_configuration.toolbox_interval = { start = "07:00:00", end = "08:00:00" }
operational_configuration.availability.start_date = "2025-01-13T07:00:00Z"
operational_configuration.availability.end_date = "2025-01-27T15:00:00Z"

[[operational]]
id = "OP-01-002"
resources.resources = [ "MTN-MECH", "MTN-ELEC", "MTN-INST" ]
hours_per_day = 6.0
operational_configuration.off_shift_interval = { start = "19:00:00", end = "07:00:00" }
operational_configuration.break_interval = { start = "11:00:00", end = "12:00:00" }
operational_configuration.toolbox_interval = { start = "07:00:00", end = "08:00:00" }
operational_configuration.availability.start_date = "2025-01-13T07:00:00Z"
operational_configuration.availability.end_date = "2025-01-27T15:00:00Z"

[[operational]]
id = "OP-01-003"
resources.resources = [ "MTN-SCAF", "MTN-RIGG" ]
hours_per_day = 6.0
operational_configuration.off_shift_interval = { start = "19:00:00", end = "07:00:00" }
operational_configuration.break_interval = { start = "11:00:00", end = "12:00:00" }
operational_configuration.toolbox_interval = { start = "07:00:00", end = "08:00:00" }
operational_configuration.availability.start_date = "2025-01-13T07:00:00Z"
operational_configuration.availability.end_date = "2025-01-27T15:00:00Z"
