[package]
name = "imperium"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shared_messages = { path = "../shared_messages" }
clap = { version = "4", features = ["derive"] }
url = "2"
serde_json = "1"
strum = "0"
webbrowser = "0"
reqwest = { version = "0", features = ["blocking"] }
tokio = { version = "1", features = ["full"] }
tracing = "0"