[package]
name = "imperium"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shared_types = { path = "../shared_types" }
clap = { version = "4", features = ["derive"] }
url = "2"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
strum = "0"
webbrowser = "0"
reqwest = { version = "0", features = ["blocking"] }
tokio = { version = "1", features = ["full"] }
tracing = "0"
toml = "0.8"
clap_complete = "4"
clap_complete_nushell = "4"
