name: Deploy to remote server
on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
   
    - name: Setup SSH Key
      uses: webfactory/ssh-agent@v0.5.0
      with:
      ssh-private-key: ${{ secrets.DEPLOY_KEY }}
   
    - name: Deploy code
      uses: appleboy/ssh-action@master
      with:
      host: login1.gbar.dtu.dk
      username: cbrje
      key: ${{ secrets.SSH_PRIVATE_KEY }}
      script: |
        cd /zhome/6b/5/127255/ordinator
        git pull origin main
        zellij -l /zhome/6b/5/127255/ordinator/ordinator.kdl
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        ssh -i $SSH_PRIVATE_KEY cbrje@login1.gbar.dtu.dk
          cd /zhome/6b/5/127255/ordinator
          git pull main
          zellij -l ordinator.kdl
        EOF
