name: Deploy to remote server
on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      run: |
        ssh -i ${{ secrets.SSH_PRIVATE_KEY }} cbrje@login1.gbar.dtu.dk
          cd /zhome/6b/5/127255/ordinator
          git pull main
          zellij -l ordinator.kdl
        EOF
